// <auto-generated />
namespace SmartCasherProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class permission_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(permission_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201905240829531_permission_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
